//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BathymetryDbfToSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHSChart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHSChart()
        {
            this.CHSDepths = new HashSet<CHSDepth>();
        }
    
        public int CHSChartID { get; set; }
        public string CHSChartName { get; set; }
        public string CHSFileName { get; set; }
        public string CHSPlaceName { get; set; }
        public Nullable<double> LongitudeMin { get; set; }
        public Nullable<double> LongitudeMax { get; set; }
        public Nullable<double> LatitudeMin { get; set; }
        public Nullable<double> LatitudeMax { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHSDepth> CHSDepths { get; set; }
    }
}
