//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("BathymetryModel", "FK_CHSDepths_CHSCharts1", "CHSChart", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BathymetryDbfToSQL.CHSChart), "CHSDepth", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BathymetryDbfToSQL.CHSDepth), true)]

#endregion

namespace BathymetryDbfToSQL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class BathymetryEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new BathymetryEntities object using the connection string found in the 'BathymetryEntities' section of the application configuration file.
        /// </summary>
        public BathymetryEntities() : base("name=BathymetryEntities", "BathymetryEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BathymetryEntities object.
        /// </summary>
        public BathymetryEntities(string connectionString) : base(connectionString, "BathymetryEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BathymetryEntities object.
        /// </summary>
        public BathymetryEntities(EntityConnection connection) : base(connection, "BathymetryEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CHSChart> CHSCharts
        {
            get
            {
                if ((_CHSCharts == null))
                {
                    _CHSCharts = base.CreateObjectSet<CHSChart>("CHSCharts");
                }
                return _CHSCharts;
            }
        }
        private ObjectSet<CHSChart> _CHSCharts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CHSDepth> CHSDepths
        {
            get
            {
                if ((_CHSDepths == null))
                {
                    _CHSDepths = base.CreateObjectSet<CHSDepth>("CHSDepths");
                }
                return _CHSDepths;
            }
        }
        private ObjectSet<CHSDepth> _CHSDepths;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CHSCharts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCHSCharts(CHSChart cHSChart)
        {
            base.AddObject("CHSCharts", cHSChart);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CHSDepths EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCHSDepths(CHSDepth cHSDepth)
        {
            base.AddObject("CHSDepths", cHSDepth);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BathymetryModel", Name="CHSChart")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CHSChart : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CHSChart object.
        /// </summary>
        /// <param name="cHSChartID">Initial value of the CHSChartID property.</param>
        public static CHSChart CreateCHSChart(global::System.Int32 cHSChartID)
        {
            CHSChart cHSChart = new CHSChart();
            cHSChart.CHSChartID = cHSChartID;
            return cHSChart;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CHSChartID
        {
            get
            {
                return _CHSChartID;
            }
            set
            {
                if (_CHSChartID != value)
                {
                    OnCHSChartIDChanging(value);
                    ReportPropertyChanging("CHSChartID");
                    _CHSChartID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CHSChartID");
                    OnCHSChartIDChanged();
                }
            }
        }
        private global::System.Int32 _CHSChartID;
        partial void OnCHSChartIDChanging(global::System.Int32 value);
        partial void OnCHSChartIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CHSChartName
        {
            get
            {
                return _CHSChartName;
            }
            set
            {
                OnCHSChartNameChanging(value);
                ReportPropertyChanging("CHSChartName");
                _CHSChartName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CHSChartName");
                OnCHSChartNameChanged();
            }
        }
        private global::System.String _CHSChartName;
        partial void OnCHSChartNameChanging(global::System.String value);
        partial void OnCHSChartNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CHSFileName
        {
            get
            {
                return _CHSFileName;
            }
            set
            {
                OnCHSFileNameChanging(value);
                ReportPropertyChanging("CHSFileName");
                _CHSFileName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CHSFileName");
                OnCHSFileNameChanged();
            }
        }
        private global::System.String _CHSFileName;
        partial void OnCHSFileNameChanging(global::System.String value);
        partial void OnCHSFileNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CHSPlaceName
        {
            get
            {
                return _CHSPlaceName;
            }
            set
            {
                OnCHSPlaceNameChanging(value);
                ReportPropertyChanging("CHSPlaceName");
                _CHSPlaceName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CHSPlaceName");
                OnCHSPlaceNameChanged();
            }
        }
        private global::System.String _CHSPlaceName;
        partial void OnCHSPlaceNameChanging(global::System.String value);
        partial void OnCHSPlaceNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> LongitudeMin
        {
            get
            {
                return _LongitudeMin;
            }
            set
            {
                OnLongitudeMinChanging(value);
                ReportPropertyChanging("LongitudeMin");
                _LongitudeMin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LongitudeMin");
                OnLongitudeMinChanged();
            }
        }
        private Nullable<global::System.Double> _LongitudeMin;
        partial void OnLongitudeMinChanging(Nullable<global::System.Double> value);
        partial void OnLongitudeMinChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> LongitudeMax
        {
            get
            {
                return _LongitudeMax;
            }
            set
            {
                OnLongitudeMaxChanging(value);
                ReportPropertyChanging("LongitudeMax");
                _LongitudeMax = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LongitudeMax");
                OnLongitudeMaxChanged();
            }
        }
        private Nullable<global::System.Double> _LongitudeMax;
        partial void OnLongitudeMaxChanging(Nullable<global::System.Double> value);
        partial void OnLongitudeMaxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> LatitudeMin
        {
            get
            {
                return _LatitudeMin;
            }
            set
            {
                OnLatitudeMinChanging(value);
                ReportPropertyChanging("LatitudeMin");
                _LatitudeMin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LatitudeMin");
                OnLatitudeMinChanged();
            }
        }
        private Nullable<global::System.Double> _LatitudeMin;
        partial void OnLatitudeMinChanging(Nullable<global::System.Double> value);
        partial void OnLatitudeMinChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> LatitudeMax
        {
            get
            {
                return _LatitudeMax;
            }
            set
            {
                OnLatitudeMaxChanging(value);
                ReportPropertyChanging("LatitudeMax");
                _LatitudeMax = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LatitudeMax");
                OnLatitudeMaxChanged();
            }
        }
        private Nullable<global::System.Double> _LatitudeMax;
        partial void OnLatitudeMaxChanging(Nullable<global::System.Double> value);
        partial void OnLatitudeMaxChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BathymetryModel", "FK_CHSDepths_CHSCharts1", "CHSDepth")]
        public EntityCollection<CHSDepth> CHSDepths
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CHSDepth>("BathymetryModel.FK_CHSDepths_CHSCharts1", "CHSDepth");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CHSDepth>("BathymetryModel.FK_CHSDepths_CHSCharts1", "CHSDepth", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BathymetryModel", Name="CHSDepth")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CHSDepth : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CHSDepth object.
        /// </summary>
        /// <param name="cHSDepthID">Initial value of the CHSDepthID property.</param>
        public static CHSDepth CreateCHSDepth(global::System.Int32 cHSDepthID)
        {
            CHSDepth cHSDepth = new CHSDepth();
            cHSDepth.CHSDepthID = cHSDepthID;
            return cHSDepth;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CHSDepthID
        {
            get
            {
                return _CHSDepthID;
            }
            set
            {
                if (_CHSDepthID != value)
                {
                    OnCHSDepthIDChanging(value);
                    ReportPropertyChanging("CHSDepthID");
                    _CHSDepthID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CHSDepthID");
                    OnCHSDepthIDChanged();
                }
            }
        }
        private global::System.Int32 _CHSDepthID;
        partial void OnCHSDepthIDChanging(global::System.Int32 value);
        partial void OnCHSDepthIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CHSChartID
        {
            get
            {
                return _CHSChartID;
            }
            set
            {
                OnCHSChartIDChanging(value);
                ReportPropertyChanging("CHSChartID");
                _CHSChartID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CHSChartID");
                OnCHSChartIDChanged();
            }
        }
        private Nullable<global::System.Int32> _CHSChartID;
        partial void OnCHSChartIDChanging(Nullable<global::System.Int32> value);
        partial void OnCHSChartIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> LineValue
        {
            get
            {
                return _LineValue;
            }
            set
            {
                OnLineValueChanging(value);
                ReportPropertyChanging("LineValue");
                _LineValue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LineValue");
                OnLineValueChanged();
            }
        }
        private Nullable<global::System.Double> _LineValue;
        partial void OnLineValueChanging(Nullable<global::System.Double> value);
        partial void OnLineValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Longitude
        {
            get
            {
                return _Longitude;
            }
            set
            {
                OnLongitudeChanging(value);
                ReportPropertyChanging("Longitude");
                _Longitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Longitude");
                OnLongitudeChanged();
            }
        }
        private Nullable<global::System.Double> _Longitude;
        partial void OnLongitudeChanging(Nullable<global::System.Double> value);
        partial void OnLongitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Latitude
        {
            get
            {
                return _Latitude;
            }
            set
            {
                OnLatitudeChanging(value);
                ReportPropertyChanging("Latitude");
                _Latitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Latitude");
                OnLatitudeChanged();
            }
        }
        private Nullable<global::System.Double> _Latitude;
        partial void OnLatitudeChanging(Nullable<global::System.Double> value);
        partial void OnLatitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Depth
        {
            get
            {
                return _Depth;
            }
            set
            {
                OnDepthChanging(value);
                ReportPropertyChanging("Depth");
                _Depth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Depth");
                OnDepthChanged();
            }
        }
        private Nullable<global::System.Double> _Depth;
        partial void OnDepthChanging(Nullable<global::System.Double> value);
        partial void OnDepthChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BathymetryModel", "FK_CHSDepths_CHSCharts1", "CHSChart")]
        public CHSChart CHSChart
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CHSChart>("BathymetryModel.FK_CHSDepths_CHSCharts1", "CHSChart").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CHSChart>("BathymetryModel.FK_CHSDepths_CHSCharts1", "CHSChart").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CHSChart> CHSChartReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CHSChart>("BathymetryModel.FK_CHSDepths_CHSCharts1", "CHSChart");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CHSChart>("BathymetryModel.FK_CHSDepths_CHSCharts1", "CHSChart", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
